apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.secretName" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  {{- if .Values.secrets.smtpUser }}
  SMTP_USER: {{ .Values.secrets.smtpUser | quote }}
  {{- end }}
  {{- if .Values.secrets.smtpPass }}
  SMTP_PASS: {{ .Values.secrets.smtpPass | quote }}
  {{- end }}
